version: "3"

services:
  app:
    build:
      context: .
      args:
        - CI_USER_TOKEN=${CI_USER_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      # realtime update without restarting docker
      - ./eBookClub:/eBookClub
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=eBookClub
      - DB_USER=admin
      - DB_PASS=admin
    depends_on:
      - db

  db:
    image: sqllite
    environment:
      - SQL_DB=eBookClub
      - SQL_USER=admin
      - SQL_PASSWORD=admin
